# Generated by Django 5.2.2 on 2025-07-22 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_customer_address_customer_bio_customer_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='zip_code',
        ),
    ]
