# Generated by Django 5.2.2 on 2025-07-22 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_customer_address_remove_customer_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='bio',
        ),
    ]
