# Generated by Django 5.2.2 on 2025-08-12 01:26

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_accesstoken_remove_feedback_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
